=== static-x03/compensarEBX/EBX Server/webapps/ebx-manager/www/common/html/onHelp/simple/resources/schema/userServices_1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--

	Copyright © TIBCO Software Inc. 2001-2021. All rights reserved. 

	******************************************************************
	You may not use this schema unless you have a valid license to
	TIBCO EBX®. This schema is subject to and controlled by such 
	license and may not be modified.
	******************************************************************
	Reserved schema, not meant for modifications
	******************************************************************
	For security reasons, TIBCO EBX® takes back an internal definition
	of this schema. Consequently, any modifications done in this
	document will be ignored by TIBCO EBX® runtime.
	******************************************************************

-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:usd="urn:ebx-schemas:userServices_1.0" targetNamespace="urn:ebx-schemas:userServices_1.0" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
	<xs:element name="services">
		<xs:annotation>
			<xs:documentation xml:lang="en-US">
				Defines the UI services available in a data model.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
					<xs:element name="service" type="usd:ServiceType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ServiceType">
		<xs:sequence>
			<xs:element name="documentation" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation xml:lang="en-US">
						Defines the labels and descriptions for the service.
					</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="label" type="xs:string" minOccurs="1"/>
						<xs:element name="description" type="xs:string" minOccurs="0"/>
					</xs:sequence>
					<xs:attribute ref="xml:lang" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="resourcePath" minOccurs="0" type="xs:string">
				<xs:annotation>
					<xs:documentation xml:lang="en-US">
						Defines the absolute module path to the JSP or servlet.
						Examples: /services/test.jsp or /test
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="permissions" minOccurs="0">
				<xs:annotation>
					<xs:documentation xml:lang="en-US">
						Defines the permissions for the service.
					</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<!-- Java bean parameters -->
						<xs:any namespace="##any" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="class" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="activation" minOccurs="0">
				<xs:annotation>
					<xs:documentation xml:lang="en-US">
						Defines the activation for the service.
					</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="onDataModel" minOccurs="0">
							<xs:complexType>
								<xs:choice>
									<xs:element name="path" type="xs:string" minOccurs="1" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation xml:lang="en-US">
 												Attribute that specifies where the UI service will be available.
 											</xs:documentation>
										</xs:annotation>	
									</xs:element>
									<xs:element name="pathRegExp" type="xs:string" minOccurs="1">
										<xs:annotation>
											<xs:documentation xml:lang="en-US">
 												The UI service will be available on all nodes whose
 												full path in the data model match the regular expression	.
 											</xs:documentation>
										</xs:annotation>	
									</xs:element>
								</xs:choice>
							</xs:complexType>
						</xs:element>
					</xs:sequence>		
				</xs:complexType>
			</xs:element>
			<xs:element name="group" type="xs:string" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation xml:lang="en-US">
						Specifies the group of the service.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="displayInMenu" minOccurs="0" type="xs:boolean" default="true">
				<xs:annotation>
					<xs:documentation xml:lang="en-US">
						Specifies if the service is displayed in service menus.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="orderInMenu" minOccurs="0">
				<xs:annotation>
					<xs:documentation xml:lang="en-US">
						Specifies the position of this service according to all the services defined in the module.
					</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="confirmation" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="label" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
     							 	<xs:extension base="xs:string">
										<xs:attribute ref="xml:lang" use="optional"/>
     								 </xs:extension>
    							</xs:simpleContent>
							</xs:complexType>		
						</xs:element>
					</xs:sequence>
					<xs:attribute name="disable" type="xs:boolean" use="optional"/>		
				</xs:complexType>
			</xs:element>
			<xs:element name="defaultPermission" minOccurs="0">
				<xs:annotation>
					<xs:documentation xml:lang="en-US">
						Specifies the default permission of the service.
					</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="enabled" />
						<xs:enumeration value="disabled" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation xml:lang="en-US">
					Name of the service.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== static-x03/compensarEBX/EBX Server/webapps/ebx-addon-adix/WEB-INF/ebx/schema/ebx-addon-adix-dataexchange_services.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--XML for user services generated from EBX5 DMA instance [reference=DEX] on Wed May 02 11:55:52 ICT 2018 by user [khoi].-->
<services xmlns="urn:ebx-schemas:userServices_1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="urn:ebx-schemas:userServices_1.0 http://schema.orchestranetworks.com/userServices_1.0.xsd">
	<service name="AutoMappingService">
		<documentation id="service.AutoMappingService" />
		<resourcePath>/dataexchange?action=AutoMappingService</resourcePath>
		<permissions class="com.orchestranetworks.addon.adix.dataexchange.model.permissions.AdministrationItemPermissions" />
		<activation>
			<onDataModel>
				<path>/DataExchange/Application/ApplicationByType{1}</path>
			</onDataModel>
		</activation>
		<displayInMenu>true</displayInMenu>
		<orderInMenu>5</orderInMenu>
		<confirmation disable="true" />
		<defaultPermission>enabled</defaultPermission>
	</service>
	<service name="CleanAllConfiguration">
		<documentation id="service.CleanAllConfiguration" />
		<resourcePath>/dataexchange?action=CleanAllConfigurationWait</resourcePath>
		<activation>
			<onDataModel>
				<pathRegExp>/</pathRegExp>
			</onDataModel>
		</activation>
		<displayInMenu>true</displayInMenu>
		<orderInMenu>1</orderInMenu>
		<confirmation disable="false">
			<label id="service.CleanAllConfiguration.confirmation.label" />
		</confirmation>
		<defaultPermission>enabled</defaultPermission>
	</service>
	<service name="CleanUnusedPathsService">
		<documentation id="service.CleanUnusedPathsService" />
		<resourcePath>/dataexchange?action=CleanUnusedPathsWait</resourcePath>
		<activation>
			<onDataModel>
				<path>/DataExchange/Path/Path</path>
			</onDataModel>
		</activation>
		<displayInMenu>true</displayInMenu>
		<confirmation disable="true" />
		<defaultPermission>enabled</defaultPermission>
	</service>
	<service name="DeletionDataMappingService">
		<documentation id="service.DeletionDataMappingService" />
		<resourcePath>/dataexchange?action=DeletionDataMappingWait</resourcePath>
		<activation>
			<onDataModel>
				<path>/DataExchange/Application/ApplicationByType{+}</path>
			</onDataModel>
		</activation>
		<displayInMenu>true</displayInMenu>
		<orderInMenu>6</orderInMenu>
		<confirmation disable="false">
			<label id="service.DeletionDataMappingService.confirmation.label" />
		</confirmation>
		<defaultPermission>enabled</defaultPermission>
	</service>
	<service name="DeletionService">
		<documentation id="service.DeletionService" />
		<resourcePath>/dataexchange?action=DeletionService</resourcePath>
		<permissions class="com.orchestranetworks.addon.adix.dataexchange.model.permissions.AdministrationItemPermissions" />
		<activation>
			<onDataModel>
				<path>/DataExchange/Application/ApplicationByType{1}</path>
			</onDataModel>
		</activation>
		<displayInMenu>true</displayInMenu>
		<orderInMenu>2</orderInMenu>
		<confirmation disable="true" />
		<defaultPermission>enabled</defaultPermission>
	</service>
	<service name="DEXConfigurationSnipletServlet">
		<resourcePath>/DataExchangeSnipletServlet</resourcePath>
		<activation>
			<onDataModel>
				<path>/</path>
			</onDataModel>
		</activation>
		<displayInMenu>false</displayInMenu>
		<confirmation disable="false" />
		<defaultPermission>enabled</defaultPermission>
	</service>
	<service name="GenerationService">
		<documentation id="service.GenerationService" />
		<resourcePath>/dataexchange?action=GenerationService</resourcePath>
		<permissions class="com.orchestranetworks.addon.adix.dataexchange.model.permissions.GenerationModelPermissions" />
		<activation>
			<onDataModel>
				<path>/DataExchange/Application/ApplicationByType{1}</path>
			</onDataModel>
		</activation>
		<displayInMenu>true</displayInMenu>
		<orderInMenu>1</orderInMenu>
		<confirmation disable="true" />
		<defaultPermission>enabled</defaultPermission>
	</service>
	<service name="PurgationService">
		<documentation id="service.PurgationService" />
		<resourcePath>/dataexchange?action=PurgationService</resourcePath>
		<permissions class="com.orchestranetworks.addon.adix.dataexchange.model.permissions.AdministrationItemPermissions" />
		<activation>
			<onDataModel>
				<path>/DataExchange/Application/ApplicationByType{1}</path>
			</onDataModel>
		</activation>
		<displayInMenu>true</displayInMenu>
		<orderInMenu>3</orderInMenu>
		<confirmation disable="true" />
		<defaultPermission>enabled</defaultPermission>
	</service>
	<service name="RefreshHierarchicalViews">
		<documentation id="service.RefreshHierarchicalViews" />
		<resourcePath>/dataexchange?action=RefreshHierarchicalViewsWait</resourcePath>
		<activation>
			<onDataModel>
				<path>/DataExchange/DataModel/Table</path>
			</onDataModel>
		</activation>
		<displayInMenu>true</displayInMenu>
		<confirmation disable="false">
			<label id="service.RefreshHierarchicalViews.confirmation.label" />
		</confirmation>
		<defaultPermission>enabled</defaultPermission>
	</service>
	<service name="ReportDataMappingService">
		<documentation id="service.ReportDataMappingService" />
		<resourcePath>/dataexchange?action=ReportDataMappingService</resourcePath>
		<permissions class="com.orchestranetworks.addon.adix.dataexchange.permissions.DEXReportDataMappingPermissions" />
		<activation>
			<onDataModel>
				<path>/DataExchange/DataMapping/TableMapping</path>
				<path>/DataExchange/DataMapping/FieldMapping</path>
			</onDataModel>
		</activation>
		<displayInMenu>true</displayInMenu>
		<orderInMenu>5</orderInMenu>
		<confirmation disable="true" />
		<defaultPermission>enabled</defaultPermission>
	</service>
	<service name="ValidationService">
		<documentation id="service.ValidationService" />
		<resourcePath>/dataexchange?action=ValidationService</resourcePath>
		<permissions class="com.orchestranetworks.addon.adix.dataexchange.model.permissions.AdministrationItemPermissions" />
		<activation>
			<onDataModel>
				<path>/DataExchange/Application/ApplicationByType{1}</path>
			</onDataModel>
		</activation>
		<displayInMenu>true</displayInMenu>
		<orderInMenu>4</orderInMenu>
		<confirmation disable="true" />
		<defaultPermission>enabled</defaultPermission>
	</service>
	<service name="XMLExportDEXConfiguration">
		<documentation id="service.XMLExportDEXConfiguration" />
		<resourcePath>/dataexchange?action=XMLExportDEXConfigurationService</resourcePath>
		<activation>
			<onDataModel>
				<path>/</path>
			</onDataModel>
		</activation>
		<displayInMenu>true</displayInMenu>
		<orderInMenu>2</orderInMenu>
		<confirmation disable="true" />
		<defaultPermission>enabled</defaultPermission>
	</service>
	<service name="XMLExportPreferencesService">
		<documentation id="service.XMLExportPreferencesService" />
		<resourcePath>/dataexchange?action=XMLExportPreferencesService</resourcePath>
		<activation>
			<onDataModel>
				<path>/DataExchange/Application/ApplicationInterfaceConfiguration{+} /DataExchange/Application/ApplicationInterfaceConfiguration</path>
			</onDataModel>
		</activation>
		<displayInMenu>true</displayInMenu>
		<confirmation disable="true" />
		<defaultPermission>enabled</defaultPermission>
	</service>
	<service name="XMLImportDEXConfiguration">
		<documentation id="service.XMLImportDEXConfiguration" />
		<resourcePath>/dataexchange?action=XMLImportDEXConfigurationService</resourcePath>
		<activation>
			<onDataModel>
				<path>/</path>
			</onDataModel>
		</activation>
		<displayInMenu>true</displayInMenu>
		<orderInMenu>3</orderInMenu>
		<confirmation disable="true" />
		<defaultPermission>enabled</defaultPermission>
	</service>
</services>

=== static-x03/compensarEBX/EBX Server/webapps/ebx-addon-adix/WEB-INF/ebx/schema/datamodeler-configuration_services.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--XML for user services generated from EBX5 DMA instance [reference=DML] on Wed Feb 08 13:37:00 ICT 2017 by user [admin].-->
<services xmlns="urn:ebx-schemas:userServices_1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="urn:ebx-schemas:userServices_1.0 http://schema.orchestranetworks.com/userServices_1.0.xsd">
	<service name="DMLSnipletServlet">
		<resourcePath>/DataExchangeSnipletServlet</resourcePath>
		<activation>
			<onDataModel>
				<path>/root/DataModel</path>
			</onDataModel>
		</activation>
		<displayInMenu>false</displayInMenu>
		<confirmation disable="false" />
		<defaultPermission>enabled</defaultPermission>
	</service>
	<service name="generateToXSD">
		<documentation id="service.generateToXSD" />
		<resourcePath>/datamodeler?service_name=generateToXSD&amp;action=generateWaiting</resourcePath>
		<permissions class="com.orchestranetworks.addon.adix.dataexchange.datamodelgenerator.model.AdministrationPermission" />
		<activation>
			<onDataModel>
				<path>/root/DataModel{1}</path>
			</onDataModel>
		</activation>
		<displayInMenu>true</displayInMenu>
		<orderInMenu>2</orderInMenu>
		<confirmation disable="true" />
		<defaultPermission>enabled</defaultPermission>
	</service>
	<service name="ImportDescription">
		<documentation id="service.ImportDescription" />
		<resourcePath>/datamodeler?service_name=importDescription&amp;action=uploadFile</resourcePath>
		<permissions class="com.orchestranetworks.addon.adix.dataexchange.datamodelgenerator.model.AdministrationPermission" />
		<activation>
			<onDataModel>
				<path>/root/DataModel{1}</path>
			</onDataModel>
		</activation>
		<displayInMenu>true</displayInMenu>
		<orderInMenu>1</orderInMenu>
		<confirmation disable="true" />
		<defaultPermission>enabled</defaultPermission>
	</service>
</services>
